import {  Roboto} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Hero from "./sections/Hero";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight:['300','900']
});


export const metadata = {
  title: "Infinite-Journeys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.variable} antialiased`}>
  <Header/>
  <Hero/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
